print('Hello.')
name = input('What is your name?\n')
print('Hello, %s.' % name)
favourite_colour = input('What is your favourite colour?\n')
print('My favourite colour is %s too.' % favourite_colour)
favourite_food = input('What is your favourite food?\n')
print('Mine is %s too!' % favourite_food)